spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false
  liquibase.enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    initialization-mode: embedded
#    data: data1.sql
  jpa:
    show-sql: false
jpa:
  database-platform: org.hibernate.dialect.H2Dialect


